# Taps
tap "chef/chef"
tap "dcchambers/tap"
tap "eth-p/software"
tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "instrumenta/instrumenta"
# tap "versent/taps" #saml2aws migrated to homebrew core.
tap "teamookla/speedtest"
tap "vmware-tanzu/carvel"

# Brew Formula (CLI tools)
brew "asciinema"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "chrome-cli"
brew "darksky-weather"
brew "dhall-json"
brew "eth-p/software/bat-extras"
brew "exa"
brew "ffmpeg"
brew "ffsend"
brew "fish"
brew "fzf"
brew "gist"
brew "git"
brew "gh"
brew "glow"
brew "go"
brew "go-jsonnet"
brew "googler"
brew "goto"
brew "hashicorp/tap/vault"
brew "heroku/brew/heroku"
brew "httpie"
brew "hub"
brew "instrumenta/instrumenta/kubeval"
brew "jq"
#brew "jsonnet" #Conflicts with go-jsonnet
brew "kubernetes-cli" #Minikube dependency, but useful to list still
brew "lynx"
brew "mas"
brew "micro"
brew "minikube"
brew "most"
brew "neofetch"
brew "nmap"
brew "nnn"
brew "node"
brew "notekeeper"
brew "pandoc"
brew "plantuml"
brew "prettyping"
brew "python"
brew "ranger"
brew "rbenv"
brew "rbenv-vars"
brew "ripgrep"
brew "rga"
brew "ruby-build"
#brew "rust" #Let's try just using rustup.
brew "rustup-init"
brew "shellcheck"
brew "speedtest" #Official Ookla speedtest
brew "speedtest-cli" #From github.com/sivel/speedtest-cli
brew "sqlite"
brew "sshuttle"
brew "task"
brew "tealdeer" #tldr.sh rust implementation
brew "terminal-notifier"
brew "tmux"
brew "transmission-cli"
brew "tree"
brew "tty-clock"
brew "saml2aws"
brew "vim"
brew "vendir"
brew "watson"
brew "wget"
brew "yarn"
brew "youtube-dl"

# Casks (.app programs)
cask "atom"
cask "background-music"
cask "basictex"
cask "calibre"
cask "chefdk"
cask "db-browser-for-sqlite"
cask "docker"
cask "firefox"
cask "firefox-developer-edition"
cask "firefox-nightly"
#cask "google-chrome" #Managed by IT dept
cask "google-chrome-canary"
cask "google-cloud-sdk"
cask "itsycal"
cask "kap"
cask "keybase"
cask "macdown"
cask "mark-text"
cask "muzzle"
cask "notable"
cask "numi"
cask "postman"
cask "rectangle"
cask "transmission"
cask "typora"
cask "visual-studio-code"
cask "vlc"
#cask "zoom" #Managed by IT dept
